= Kontainers
:imagesdir: docs/images
ifdef::env-github[]
:imagesdir: https://github.com/microkt/kontainers/blob/main/docs/images/
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:note-caption: :information_source:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]
:toc: macro
:toclevels: 3
:toc-title:

image::https://github.com/microkt/kontainers/actions/workflows/ci.yml/badge.svg[Build Kontainers]

== Purpose

Kontainers is a Kotlin framework providing the capability to run Open Container Images (OCI) on
Docker, Kubernetes, and possibly other platforms in the near future. This can be valuable in cases where you want to run a
database or messaging system for integration testing and then tear down such
resources after tests complete.

Kontainers enables users to write and run integration tests locally with 
[Docker Desktop], while also utilizing modern, Kubernetes based CI/CD
systems that may not permit or support the Docker runtime.

Kontainers provides a platform-agnostic Kontainer specification that allows users
to define a request to run a container or Docker and K8S. The specification is then
used by a Kontainer factory to start the container on either Docker or Kubernetes,
depending on the capabilities of the platform on which your code is run.

```mermaid
  flowchart LR;
    S1([Redis Kontainer Spec]) & S2([MySQL Kontainer Spec]) & S3([PostgreSQL Kontainer Spec]) & S4([Any Kontainer Spec]) -- create with --> Factory([Kontainer Factory])
    Factory -- uses --> Platform{Determine Platform}
    Platform -. Docker .-> DR(Docker Kontainer Runner)
    Platform -. K8S .-> KR(Kubernetes Kontainer Runner) 
    Platform -. Future Runtime .-> X(Future Kontainer Runner)
    Factory === produces ===> RK([Redis Kontainer]) & MK([MySQL Kontainer]) & PK([PostgreSQL Kontainer]) & AK([Any Kontainer])
```

== Using Kontainers

IMPORTANT: Kontainers is currently prerelease software. API contracts and
behavior are subject to change.

Please refer to the https://microkt.io/docs/kontainers/overview[Kontainers' Documentation].

== Contributing

If you'd like to fix a bug or contribute a new container, fork this repository and create a pull request.

If you'd like to introduce a new feature or change something related to Kontainers'
prerelease architecture, start a discussion or create an issue to discuss changes with
the group before writing code.

=== Understanding Tests

There are three types of tests in Kontainers, each is assigned `@Tag` on a test suite:
unit tests, Docker integration tests, and Kubernetes integration tests.
Unit tests, `@Tag("unit")`, can run without a Docker or Kubernetes being available. Docker
integration tests, `@Tag("docker")`, require the Docker daemon to be running in the test
environment. Kubernetes integration tests, `@Tag("kubernetes")`, must be run in a K8S pod
or have K8S infrastructure, such as https://minikube.sigs.k8s.io/docs/start/[Minikube],
available for testing.

==== Docker Integration Tests

Docker integration tests have been verified to work on Linux & macOS, Windows is not
currently supported.

Linux requires a running Docker daemon and the current user is a member of the
`docker` group. Validated on Ubuntu 20.04.

macOS requires Docker Desktop to be installed and running.

==== Kubernetes Integration Tests

Kubernetes integration tests have been verified to work on Linux with Minkube and
in integration testing environments where the integration test launches Kontainers
into its own namespace.

Testing with Minikube requires Linux, and Minikube's IP address to be exported to the
environment. You can do this by running: `export MINIKUBE_IP=$(minikube ip)`

TIP: If you exported `MINIKUBE_IP` and tests fail to start, restart the
Gradle daemon with either `./gradlew --stop` or `pkill -f GradleDaemon`
