name: Build Kontainers

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  TERM: dumb
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

jobs:
  build:
    name: Build & Check
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Gradle Cache
        id: cache-gradle-files
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build & Check
        run: |
          ./gradlew --no-daemon --continue check

      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: unit-test-results
          path: |
            ${{ github.workspace }}/**/build/test-results/**/*.xml
            ${{ github.workspace }}/**/build/reports/ktlint/**/*.xml
          if-no-files-found: error

  docker:
    name: Docker Integration Tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Gradle Cache
        id: cache-gradle-files
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Docker Integration Test
        run: ./gradlew --no-daemon -x ktLintCheck dockerIntegrationTest

      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: docker-itest-results
          path: ${{ github.workspace }}/**/build/test-results/**/*.xml
          if-no-files-found: error

  kubernetes:
    name: Kubernetes Cluster Integration Tests
    runs-on:
      - self-hosted
      - Linux
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Gradle Cache
        id: cache-gradle-files
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Kubernetes Integration Test
        run: |
          ./gradlew --no-daemon -x ktLintCheck kubernetesIntegrationTest

      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: kubernetes-itest-results
          path: ${{ github.workspace }}/**/build/test-results/**/*.xml
          if-no-files-found: error

  report:
    name: Report Checks
    runs-on: ubuntu-20.04
    if: always()
    needs:
      - build
      - docker
      - kubernetes
    steps:
      - name: Pull Check Action
        uses: actions/checkout@v2
        with:
          repository: microkt/code-check-report-action
          path: check-action
          ssh-key: ${{ secrets.ACTIONS_READ_KEY }}
          ref: v0.1.0

      - name: Download Unit Tests
        uses: actions/download-artifact@v2
        with:
          name: unit-test-results

      - name: Download Docker Tests
        uses: actions/download-artifact@v2
        with:
          name: docker-itest-results

      - name: Download Kubernetes Tests
        uses: actions/download-artifact@v2
        with:
          name: kubernetes-itest-results

      - name: List files
        run: |
          ls -la
          find

      - name: Publish Checks
        if: github.event_name == 'pull_request' && always()
        uses: ./check-action
        with:
          token: ${{ github.token }}
