name: Public Documentation

on:
  workflow_dispatch:

env:
  TERM: dumb
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

jobs:
  build:
    name: Prepare Documentation
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Gradle Cache
        id: cache-gradle-files
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build & Check
        run: |
          ./gradlew dokkaHtmlMultiModule

      -name: Publish Docs
       uses: peaceiris/actions-gh-pages@v3
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         cname: kontainers.microkt.io
         publish_dir: ./build/dokka/htmlMultiModule/
         desination_dir: api/current
